apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    github.com/project-slug: QualiNext/cs2018
spec:
  type: service
  lifecycle: production
  owner: demo@leumi.co.il
  system: lcb

---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: demo
owner_email: demo@leumi.co.il
inputs:
  project: lcb
  zone: fe
  AWS Region: us-west-1
grains:
  apigw:
    name: apigw
    inputs:
      swager_file_path: '77755'
  postgresql:
    name: postgresql
    inputs:
      name: rrr
  lambda:
    name: lambda
    inputs:
      '0':
        name: lambda-tests
        endpoints:
          - path: /lambda-1
            method: GET
          - path: /lambda-1/admin
            method: POST
      '1':
        name: lambda-2tests
        endpoints:
          - path: /lambda-2
            method: POST
        endpoints[0]:
          method: POS
          path: /lambda-
      '2':
        name: 'lambda-3 '
        endpoints:
          - path: /lambda-3/data
            method: GET
          - path: /lambda-3/update
            method: PUT
metadata:
  name: demo
