apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    github.com/project-slug: QualiNext/cs2018
spec:
  type: service
  lifecycle: production
  owner: demo@leumi.co.il
  system: lcb

---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: demo
owner_email: demo@leumi.co.il
inputs:
  project: lcb
  zone: fe
  AWS Region: us-west-1
grains:
  apigw:
    name: apigw
    inputs:
      swager_file_path: '77755'
  postgresql:
    name: postgresql
    inputs:
      name: rrr
  lambda:
    name: lambda
    inputs:
      lambdas:
        - name: lambda-1
          path: /lambda-1
          method: GET
        - name: lambda-2
          path: /lambda-2
          method: POST
      lambdas[0]:
        method: post
        name: lambda-1g
      lambdas[1]:
        method: t
metadata:
  name: demo
