null

---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: demo
owner_email: demo@leumi.co.il
inputs:
  project: lcb
  zone: fe
  AWS Region: us-west-1
grains:
  apigw:
    name: apigw
    inputs:
      source:
        commit: default-commit-value
      inputs:
        - name: 22
  postgresql:
    name: postgresql
    inputs:
      name: rrr
  lambda:
    name: lambda
    inputs:
      source:
        commit: default-commit-value
      inputs:
        - name: lambda-4
          endpoints:
            - path: /lambda-4
              method: GET
            - path: /lambda-1/admin
              method: POST
        - name: lambda-2
          endpoints:
            - path: /lambda-2
              method: POST
        - name: lambda-3
          endpoints:
            - path: /lambda-3/data
              method: GET
            - path: /lambda-3/update
              method: PUT
metadata:
  name: demo
