apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: The place to be, for great artists
  annotations:
    example.com/service-discovery: artistweb
spec:
  type: website
  lifecycle: production
  owner: aa
  system: public-websites

---
apiVersion: leumi.io/v1alpha1
kind: Environment
environment_name: demo
state: active
owner_email: demo@leumi.com
grains:
  KMS-Key:
    kind: blueprint
    spec:
      source:
        commit: f91427017aa816dbf5d267076d8c56e7da84a38a
      inputs:
        name: 33eeee
        sha256: 444trrr
        target: 555yttt
  lambda:
    kind: blueprint
    spec:
      source:
        commit: f91427017aa816dbf5d267076d8c56e7da84a38a33333
      inputs:
        lambdas:
          - demo1
          - demo2
        config:
          - path: /
            method: GET
            lambda: demo1
          - path: /
            method: GET
            lambda: demo2
  S3-Webapp:
    kind: blueprint
    spec:
      source:
        commit: f91427017aa816dbf5d267076d8c56e7da84a38a
      inputs:
        name: demo33
        port: '44344'
metadata:
  name: demo
spec:
  type: service
