apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    github.com/project-slug: 'QualiNext/cs2018'
spec:
  type: service
  owner: demo@leumi.co.il
  system: lcb
  lifecycle: production
---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: demo
owner_email: demo@leumi.co.il
inputs:
  project: lcb
  zone: fe
  AWS Region: us-west-1
grains: 
  lambda:
    kind: blueprint
    spec: 
      source: 
        commit: 'f91427017aa816dbf5d26'
      inputs: 
        - version: '{{ .inputs.["Application Version"] }}'
        - name: "lambda-1"
          endpoints:
            - path: "/lambda-1"
              method: "GET"
            - path: "/lambda-1/admin"
              method: "POST"
        - name: "lambda-2"
          endpoints:
            - path: "/lambda-2"
              method: "POST"
        - name: "lambda-3"
          endpoints:
            - path: "/lambda-3/data"
              method: "GET"
            - path: "/lambda-3/update"
              method: "PUT"
  postgresql:
    kind: blueprint
    spec: 
      source: 
        commit: 'f91427017aa816dbf5d26'
      inputs: 
        - name: 'demo'
      outputs:
        - name
  apigw:
    kind: blueprint
    spec: 
      source: 
        commit: 'f91427017aa816dbf5d26'
      inputs: 
        - name: 'demo'
      outputs:
        - name

metadata:
  name: demo
spec:
  type: service
