apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tests
  annotations:
    github.com/project-slug: 'QualiNext/cs2018'
spec:
  type: service
  lifecycle: experimental
  owner: dbs
  system: examples
  providesApis: [torque-all-apis]
---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: Production Environment
owner_email: amir.r@quali.com
blueprint:
  name: Webgame on S3 (TF)
  repository_name: ProductionBPs
  commit: 6723c086a9f4e43b3745364348fd78d14091b88d
inputs:
  Name: webapp-bucket
  Name Prefix: torque-demo
  AWS Region: us-west-1
grains:
  S3-Webapp:
    source:
      commit: f91427017aa816dbf5d267076d8c56e7da84a38a
    inputs:
      name: webapp-bucket
      port: 8080
  KMS-Key:
    source:
      commit: f91427017aa816dbf5d267076d8c56e7da84a38a
    inputs:
      name: kms-key
      hase: true
      target: https
metadata:
  name: tests
  annotations:
    github.com/project-slug: 'QualiNext/cs2018'
spec:
  type: service
  lifecycle: experimental
  owner: dbs
  system: examples
  providesApis: [torque-all-apis]
