apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    github.com/project-slug: QualiNext/cs2018
spec:
  type: service
  lifecycle: production
  owner: demo@leumi.co.il
  system: lcb

---
apiVersion: leumi.io/v1alpha1
kind: Environment
state: active
environment_name: demo
owner_email: demo@leumi.co.il
inputs:
  project: lcb
  zone: fe
  AWS Region: us-west-1
grains:
  apigw:
    name: apigw
    inputs:
      swager_file_path: '77755'
  postgresql:
    source:
      commit: default-commit
    inputs:
      name: ttt
metadata:
  name: demo
