apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-api
  description: The place to be, for great artists
  annotations:
    jenkins.io/job-full-name: "default:back"
spec:
  type: website
  lifecycle: production
  owner: user:default/moticohen_2
  system: lcb


