kind: environment
environment_name: Event microservice Production
description: Kubernetes based deployment of the event-ms optimized for production
state: active
owner_email: user@quali.com
blueprint:
  name: test-1
  repository_name: cloud-native-application
  branch: main
  commit: 697d1a81fed31adf2eb9e75349def8245f80f87d
inputs:
  '333': '333'
  www: eeee
  tt: tttt
grains:
  KMS-Key:
    source:
      commit: f91427017aa816dbf5d267076d8c56e7da84a38a
    inputs:
      name: namee
      sha256: ttt
      target: eeee
  lambda:
    source:
      commit: f91427017aa816dbf5d26
    inputs:
      name: ttt
      apigee: ttt
