openapi: "3.0.0"
info:
  version: 4.3.0
  title: refael_demo
  license:
    name: MIT
servers:
  - url: http://leumi.lcb.net/v7
paths:
  /customers:
    get:
      summary: List all artists
metadata:
  name: leumi-demo
spec:
  type: service
