apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: Component description
  links: []
  tags: []
  annotations: {}
  system: devops
  torqe:
    inputs:
      name: test
    grains:
      lambda.lambda:
        commits: "122222222222"
spec:
  type: service
  lifecycle: experimental
  owner: owner